!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
' uncomment the following line and comment the first to use locally
' !include C4_Container.puml

' Styling
' ##################################

skinparam rectangle<<node>> {
    Shadowing false
    StereotypeFontSize 0
    FontColor #000000
    BorderColor #A2A2A2
    BorderStyle solid
}

' Elements
' ##################################
!define Deployment_Node(e_alias, e_label) rectangle "==e_label" <<node>> as e_alias
!define Deployment_Node(e_alias, e_label, e_type) rectangle "==e_label\n<size:TECHN_FONT_SIZE>[e_type]</size>" <<node>> as e_alias