@startuml

!$UseTheme=C4_FirstTest

!if %variable_exists("RELATIVE_INCLUDE")
  !include ./TestThemeTemplate.puml
!else
  !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/v2.6.0/percy/TestThemeTemplate.puml
!endif

@enduml
