!$THEME = "C4Language_italian"

!$BOUNDARY_LEGEND_TEXT ?= "confine"

!$LEGEND_TITLE_TEXT ?= "Legenda"

!$LEGEND_BOUNDARY ?= "confine"
!$LEGEND_BOUNDARY_PRE_PART ?= "confine del "
!$LEGEND_BOUNDARY_POST_PART ?= ""

!$LEGEND_SHADOW_TEXT ?= "ombra"
!$LEGEND_NO_SHADOW_TEXT ?= "nessuna ombra"
!$LEGEND_NO_FONT_BG_TEXT ?= "ultimo colore del testo e dello sfondo"
!$LEGEND_NO_FONT_TEXT ?= "ultimo colore del testo"
!$LEGEND_NO_BG_TEXT ?= "ultimo colore dello sfondo"
!$LEGEND_NO_LINE_TEXT ?= "ultimo colore della linea"
!$LEGEND_ROUNDED_BOX ?= "scatola arrotondata"
!$LEGEND_EIGHT_SIDED ?= "otto lati"
!$LEGEND_DOTTED_LINE ?= "punteggiato"
!$LEGEND_DASHED_LINE ?= "tratteggiato"
!$LEGEND_BOLD_LINE ?= "grassetto"
!$LEGEND_SOLID_LINE ?= "solido"
' !$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= "transparent, "
!$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= ""
!$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= "tratteggiato, "
' !$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= ""
!$LEGEND_THICKNESS ?= "spessore"
!$SKETCH_FOOTER_WARNING ?= "Avvertimento:"
!$SKETCH_FOOTER_TEXT ?= "Creato per discussione, deve essere convalidato"

!$COMPONENT_LEGEND_TEXT ?= "componente"
!$EXTERNAL_COMPONENT_LEGEND_TEXT ?= "componente esterno"

!$CONTAINER_LEGEND_TEXT ?= "contenitore"
!$CONTAINER_BOUNDARY_TYPE ?= "contenitore"
!$CONTAINER_BOUNDARY_LEGEND_TEXT ?= "confine del contenitore"
!$EXTERNAL_CONTAINER_LEGEND_TEXT ?= "contenitore esterno"

!$PERSON_LEGEND_TEXT ?= "persona"
!$EXTERNAL_PERSON_LEGEND_TEXT ?= "persona esterna"

!$SYSTEM_LEGEND_TEXT ?= "sistema"
!$SYSTEM_BOUNDARY_TYPE ?= "sistema"
!$SYSTEM_BOUNDARY_LEGEND_TEXT ?= "confine del sistema"
!$EXTERNAL_SYSTEM_LEGEND_TEXT ?= "sistema esterno"

!$ENTERPRISE_BOUNDARY_TYPE ?= "impresa"
!$ENTERPRISE_BOUNDARY_LEGEND_TEXT ?= "confine dell'impresa"

!$NODE_LEGEND_TEXT ?= "nodo"
