!$THEME = "C4Language_korean"

!$BOUNDARY_LEGEND_TEXT ?= "경계"

!$LEGEND_TITLE_TEXT ?= "범례"

!$LEGEND_BOUNDARY ?= "경계"
' !$LEGEND_BOUNDARY_PRE_PART ?= ""
' !$LEGEND_BOUNDARY_POST_PART ?= " " + $LEGEND_BOUNDARY

!$LEGEND_SHADOW_TEXT ?= "그림자"
!$LEGEND_NO_SHADOW_TEXT ?= "그림자 없음"
!$LEGEND_NO_FONT_BG_TEXT ?= "마지막 텍스트 및 배경 색상"
!$LEGEND_NO_FONT_TEXT ?= "마지막 텍스트 색상"
!$LEGEND_NO_BG_TEXT ?= "마지막 배경 색상"
!$LEGEND_NO_LINE_TEXT ?= "마지막 선 색상"
!$LEGEND_ROUNDED_BOX ?= "둥근 상자"
!$LEGEND_EIGHT_SIDED ?= "팔각형"
!$LEGEND_DOTTED_LINE ?= "점선"
!$LEGEND_DASHED_LINE ?= "대시선"
!$LEGEND_BOLD_LINE ?= "굵은 선"
!$LEGEND_SOLID_LINE ?= "실선"
' !$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= "transparent, "
!$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= ""
!$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= "대시선, "
' !$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= ""
!$LEGEND_THICKNESS ?= "두께"

!$SKETCH_FOOTER_WARNING ?= "경고:"
!$SKETCH_FOOTER_TEXT ?= "토론을 위해 작성되었으며 검증이 필요합니다"

!$COMPONENT_LEGEND_TEXT ?= "구성 요소"
!$EXTERNAL_COMPONENT_LEGEND_TEXT ?= "외부 구성 요소"

!$CONTAINER_LEGEND_TEXT ?= "컨테이너"
!$CONTAINER_BOUNDARY_TYPE ?= "컨테이너"
!$CONTAINER_BOUNDARY_LEGEND_TEXT ?= "컨테이너 경계"
!$EXTERNAL_CONTAINER_LEGEND_TEXT ?= "외부 컨테이너"

!$PERSON_LEGEND_TEXT ?= "사람"
!$EXTERNAL_PERSON_LEGEND_TEXT ?= "외부 사람"

!$SYSTEM_LEGEND_TEXT ?= "시스템"
!$SYSTEM_BOUNDARY_TYPE ?= "시스템"
!$SYSTEM_BOUNDARY_LEGEND_TEXT ?= "시스템 경계"
!$EXTERNAL_SYSTEM_LEGEND_TEXT ?= "외부 시스템"

!$ENTERPRISE_BOUNDARY_TYPE ?= "기업"
!$ENTERPRISE_BOUNDARY_LEGEND_TEXT ?= "기업 경계"

!$NODE_LEGEND_TEXT ?= "노드"
