!$THEME = "C4Language_chinese"

!$BOUNDARY_LEGEND_TEXT ?= "边界"

!$LEGEND_TITLE_TEXT ?= "图例"

!$LEGEND_BOUNDARY ?= "边界"
' !$LEGEND_BOUNDARY_PRE_PART ?= ""
!$LEGEND_BOUNDARY_POST_PART ?= $LEGEND_BOUNDARY

!$LEGEND_SHADOW_TEXT ?= "阴影"
!$LEGEND_NO_SHADOW_TEXT ?= "无阴影"
!$LEGEND_NO_FONT_BG_TEXT ?= "最后的文字和背景颜色"
!$LEGEND_NO_FONT_TEXT ?= "最后的文字颜色"
!$LEGEND_NO_BG_TEXT ?= "最后的背景颜色"
!$LEGEND_NO_LINE_TEXT ?= "最后的线条颜色"
!$LEGEND_ROUNDED_BOX ?= "圆角框"
!$LEGEND_EIGHT_SIDED ?= "八边形"
!$LEGEND_DOTTED_LINE ?= "点线"
!$LEGEND_DASHED_LINE ?= "虚线"
!$LEGEND_BOLD_LINE ?= "粗线"
!$LEGEND_SOLID_LINE ?= "实线"
' !$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= "transparent, "
!$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= ""
!$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= "虚线, "
' !$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= ""
!$LEGEND_THICKNESS ?= "厚度"

!$SKETCH_FOOTER_WARNING ?= "警告:"
!$SKETCH_FOOTER_TEXT ?= "创建用于讨论，需要验证"

!$COMPONENT_LEGEND_TEXT ?= "组件"
!$EXTERNAL_COMPONENT_LEGEND_TEXT ?= "外部组件"

!$CONTAINER_LEGEND_TEXT ?= "容器"
!$CONTAINER_BOUNDARY_TYPE ?= "容器"
!$CONTAINER_BOUNDARY_LEGEND_TEXT ?= "容器边界"
!$EXTERNAL_CONTAINER_LEGEND_TEXT ?= "外部容器"

!$PERSON_LEGEND_TEXT ?= "人"
!$EXTERNAL_PERSON_LEGEND_TEXT ?= "外部人"

!$SYSTEM_LEGEND_TEXT ?= "系统"
!$SYSTEM_BOUNDARY_TYPE ?= "系统"
!$SYSTEM_BOUNDARY_LEGEND_TEXT ?= "系统边界"
!$EXTERNAL_SYSTEM_LEGEND_TEXT ?= "外部系统"

!ENTERPRISE_BOUNDARY_TYPE ?= "企业"
!$ENTERPRISE_BOUNDARY_LEGEND_TEXT ?= "企业边界"

!$NODE_LEGEND_TEXT ?= "节点"
