!$THEME = "C4Language_japanese"

!$BOUNDARY_LEGEND_TEXT ?= "境界"

!$LEGEND_TITLE_TEXT ?= "凡例"

!$LEGEND_BOUNDARY ?= "境界"
' !$LEGEND_BOUNDARY_PRE_PART ?= ""
!$LEGEND_BOUNDARY_POST_PART ?= $LEGEND_BOUNDARY

!$LEGEND_SHADOW_TEXT ?= "影"
!$LEGEND_NO_SHADOW_TEXT ?= "影なし"
!$LEGEND_NO_FONT_BG_TEXT ?= "最後のテキストと背景色"
!$LEGEND_NO_FONT_TEXT ?= "最後のテキスト色"
!$LEGEND_NO_BG_TEXT ?= "最後の背景色"
!$LEGEND_NO_LINE_TEXT ?= "最後の線色"
!$LEGEND_ROUNDED_BOX ?= "丸いボックス"
!$LEGEND_EIGHT_SIDED ?= "八角形"
!$LEGEND_DOTTED_LINE ?= "点線"
!$LEGEND_DASHED_LINE ?= "破線"
!$LEGEND_BOLD_LINE ?= "太線"
!$LEGEND_SOLID_LINE ?= "実線"
' !$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= "transparent, "
!$LEGEND_BOUNDARY_TRANSPARENT_INCL_COMA ?= ""
!$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= "破線, "
' !$LEGEND_BOUNDARY_DASHED_INCL_COMA ?= ""
!$LEGEND_THICKNESS ?= "厚さ"

!$SKETCH_FOOTER_WARNING ?= "警告:"
!$SKETCH_FOOTER_TEXT ?= "議論用に作成されたもので、検証が必要です"

!$COMPONENT_LEGEND_TEXT ?= "コンポーネント"
!$EXTERNAL_COMPONENT_LEGEND_TEXT ?= "外部コンポーネント"

!$CONTAINER_LEGEND_TEXT ?= "コンテナ"
!$CONTAINER_BOUNDARY_TYPE ?= "コンテナ"
!$CONTAINER_BOUNDARY_LEGEND_TEXT ?= "コンテナ境界"
!$EXTERNAL_CONTAINER_LEGEND_TEXT ?= "外部コンテナ"

!$PERSON_LEGEND_TEXT ?= "人"
!$EXTERNAL_PERSON_LEGEND_TEXT ?= "外部の人"

!$SYSTEM_LEGEND_TEXT ?= "システム"
!$SYSTEM_BOUNDARY_TYPE ?= "システム"
!$SYSTEM_BOUNDARY_LEGEND_TEXT ?= "システム境界"
!$EXTERNAL_SYSTEM_LEGEND_TEXT ?= "外部システム"

!$ENTERPRISE_BOUNDARY_TYPE ?= "企業"
!$ENTERPRISE_BOUNDARY_LEGEND_TEXT ?= "企業境界"

!$NODE_LEGEND_TEXT ?= "ノード"
