!theme united

!$THEME = "C4_united"

!$ELEMENT_FONT_COLOR ?= $PRIMARY_TEXT

!$ARROW_COLOR ?= $PRIMARY_LIGHT
!$ARROW_FONT_COLOR ?= $ARROW_COLOR

!$PERSON_FONT_COLOR ?= $INFO_TEXT
!$PERSON_BG_COLOR ?= $INFO
!$PERSON_BORDER_COLOR ?= $INFO_DARK

!$EXTERNAL_PERSON_FONT_COLOR ?= $INFO_DARK
!$EXTERNAL_PERSON_BG_COLOR ?= $LIGHT
!$EXTERNAL_PERSON_BORDER_COLOR ?= $INFO_DARK

!$SYSTEM_FONT_COLOR ?= $WHITE
!$SYSTEM_BG_COLOR ?= $DARK
!$SYSTEM_BORDER_COLOR ?= $DARK_DARK

!$EXTERNAL_SYSTEM_FONT_COLOR ?= $DARK_DARK
!$EXTERNAL_SYSTEM_BG_COLOR ?= $LIGHT
!$EXTERNAL_SYSTEM_BORDER_COLOR ?= $DARK_DARK

!$CONTAINER_FONT_COLOR ?= $WARNING_TEXT
!$CONTAINER_BG_COLOR ?= $WARNING
!$CONTAINER_BORDER_COLOR ?= $WARNING_DARK

!$EXTERNAL_CONTAINER_FONT_COLOR ?= $WARNING_DARK
!$EXTERNAL_CONTAINER_BG_COLOR ?= $LIGHT
!$EXTERNAL_CONTAINER_BORDER_COLOR ?= $WARNING_DARK

!$COMPONENT_FONT_COLOR ?= $PRIMARY_TEXT
!$COMPONENT_BG_COLOR ?= $PRIMARY
!$COMPONENT_BORDER_COLOR ?= $PRIMARY_DARK

!$EXTERNAL_COMPONENT_FONT_COLOR ?= $PRIMARY_DARK
!$EXTERNAL_COMPONENT_BG_COLOR ?= $LIGHT
!$EXTERNAL_COMPONENT_BORDER_COLOR ?= $PRIMARY_DARK

!$NODE_FONT_COLOR ?= $LIGHT
!$NODE_BG_COLOR ?= $SECONDARY
!$NODE_BORDER_COLOR ?= $SECONDARY_DARK

!$BOUNDARY_COLOR ?= $PRIMARY_DARK
!$BOUNDARY_BG_COLOR ?= "transparent"
!$BOUNDARY_BORDER_STYLE ?= "solid"
' border is not dashed in theme "united", remove dashed from legend text too
!$LEGEND_DASHED_BOUNDARY ?= ""
!$LEGEND_DASHED_TRANSPARENT_BOUNDARY ?= ""
!$ENTERPRISE_BOUNDARY_COLOR ?= $SYSTEM_BORDER_COLOR
!$SYSTEM_BOUNDARY_COLOR ?= $SYSTEM_BORDER_COLOR
!$CONTAINER_BOUNDARY_COLOR ?= $CONTAINER_BORDER_COLOR

!$LEGEND_TITLE_COLOR ?= $LIGHT
!$LEGEND_FONT_COLOR ?= $LIGHT
!$LEGEND_BG_COLOR ?= $SECONDARY
!$LEGEND_BORDER_COLOR ?= $SECONDARY_DARK

' <<<<<<<<<<<<< sequence diagram is styled via skinparam and style

' "C4 styled" default is no foot boxes
hide footbox

' fix wrong ReferenceHeaderFontColor
<style>
referenceHeader {
  fontcolor $INFO
}
</style>

' fix invisible SequenceDelayFontColor
<style>
sequenceDiagram {
  delay {
    FontColor $DARK
  }
}
</style>

' <<<<<<<<<<<<< end sequence diagram
